### ISSUE TITLE
App bar text not aligned 

### ISSUE THREAD

**Issue by VatsalSin** [Celesta-IITP/Celesta-2k18#7]
the text in app bar of main activity is misaligned with the drawer icon.

**Comment by sudoalgorithm** [comment]
Working on it

**Comment by adonixis** [comment]
Hi! Now it looks like this
![screenshot_1538805558](https://user-images.githubusercontent.com/1766863/46568008-ad33f000-c957-11e8-9dcf-a6f9d040b51a.png)
Should it look like this?
![1](https://user-images.githubusercontent.com/1766863/46568011-c0df5680-c957-11e8-9abb-2a92f7f1b369.png)
or this?
![2](https://user-images.githubusercontent.com/1766863/46568018-c50b7400-c957-11e8-9806-6019d33c6280.png)

**Comment by ivary43** [comment]
@adonixis  send the PR
